security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Utilisation d'un provider basé sur Doctrine pour charger les utilisateurs depuis la base de données
    providers:
        users_in_db:
            entity:
                class: App\Entity\User
                property: email  # C'est l'email qui sera utilisé pour retrouver l'utilisateur

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_db  # Utilisation du provider pour charger l'utilisateur depuis la BDD
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Contrôle d'accès basé sur les rôles
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

# Configuration spécifique pour les tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
